# pre-commit hooks available at https://github.com/SINTEF/ci-cd

- id: docs-api-reference
  name: Update API Reference in Documentation
  entry: "ci-cd create-api-reference-docs --pre-clean --pre-commit"
  language: python
  files: \.py$
  exclude: ^$
  types: [file, python]
  types_or: []
  exclude_types: []
  always_run: false
  fail_fast: false
  verbose: false
  pass_filenames: false
  require_serial: false
  description: "Update the API Reference documentation whenever a Python file is touched in the code base."
  language_version: default
  minimum_pre_commit_version: "2.16.0"
  args: []

- id: docs-landing-page
  name: Update Landing Page (index.md) for Documentation
  entry: "ci-cd create-docs-index --pre-commit"
  language: python
  files: ^README.md$
  exclude: ^$
  types: [file, markdown]
  types_or: []
  exclude_types: []
  always_run: false
  fail_fast: false
  verbose: false
  pass_filenames: false
  require_serial: false
  description: "Update the landing page (index.md) for the documentation if the source file (README.md) is changed."
  language_version: default
  minimum_pre_commit_version: "2.16.0"
  args:
    - '--replacement'
    - '(LICENSE),(LICENSE.md)'

- id: update-pyproject
  name: Update dependencies in pyproject.toml.
  entry: "ci-cd update-deps --pre-commit"
  language: python
  files: ""
  exclude: ^$
  types: []
  types_or: []
  exclude_types: []
  always_run: true
  fail_fast: false
  verbose: false
  pass_filenames: false
  require_serial: false
  description: "Update dependencies in pyproject.toml according to the latest version on PyPI."
  language_version: default
  minimum_pre_commit_version: "2.16.0"
  args: []
