site_name: "GH Action Reusable Workflows"
site_description: Documentation for GitHub Action resusable workflows
site_url: https://SINTEF.github.io/ci-cd
copyright: Copyright &copy; 2022 Casper Welzel Andersen & SINTEF

theme:
  name: material
  palette:
    scheme: default
    primary: lime
    accent: amber
  icon:
    repo: fontawesome/brands/github
    logo: material/library-outline
  favicon: assets/images/favicon.png
  language: en
  features:
    - navigation.instant
    - navigation.top

repo_name: "ci-cd"
repo_url: "https://github.com/SINTEF/ci-cd"
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/square-github
      link: https://github.com/SINTEF
      name: "SINTEF on GitHub"
    - icon: fontawesome/brands/github
      link: https://github.com/CasperWA
      name: "Casper Welzel Andersen on GitHub"
  version:
    provider: mike
    default: latest

extra_css:
  - css/reference.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - toc:
      permalink: true

plugins:
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: false
            show_root_toc_entry: true
            show_root_full_path: true
            show_object_full_path: false
            show_category_heading: false
            show_if_no_docstring: false
            show_source: true
            show_bases: true
            group_by_category: true
            heading_level: 3
            filters:
              - "!^_[^_]"
            members: null
            docstring_style: google
  - awesome-pages

nav:
  - Home: index.md
  - Workflows:
    - Overview: workflows/index.md
    - ... | flat | workflows/**
  - Hooks:
    - Overview: hooks/index.md
    - ... | flat | hooks/**
  - License: LICENSE.md
  - Changelog: CHANGELOG.md

watch:
  - "ci_cd"
